sudo: required
dist: trusty
language: cpp

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty
    packages:
    - cmake
    - libgfortran3
    - gfortran
    - libopenmpi-dev
    - openmpi-bin
    - libblas-dev
    - liblapack-dev
    - libfftw3-dev
    - libgmp-dev
    - libhdf5-serial-dev
    - libboost1.55-all-dev
    - gcc-5
    - g++-5
    - gcc-6
    - g++-6

matrix:
  include:
    - compiler: gcc
      env:
        - COMPILERXX=g++-5
        - COMPILER=gcc-5
    - compiler: gcc
      env:
        - COMPILERXX=g++-6
        - COMPILER=gcc-6
deploy:
  provider: s3
  access_key_id: $AWS_A_KEY
  secret_access_key: $AWS_S_KEY
  bucket: buildbin
  skip_cleanup: true
  region: us-west-2
  endpoint: s3-us-west-2.amazonaws.com
  local_dir: $HOME/bin
  on:
    branch: travis


before_install:
    - export CXX=$COMPILERXX CC=$COMPILER
    - env
    #Set anaconda python environment
    - cd $HOME
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - conda update --yes --quiet conda
    - conda create --yes --quiet -n testenv python=2.7 nomkl numpy scipy matplotlib tornado pyzmq cython h5py pip
    - source activate testenv
    - pip install mako mpi4py


install:
    - export C_INCLUDE_PATH=$CONDA_PREFIX/include:$C_INCLUDE_PATH
    - export CPLUS_INCLUDE_PATH=$CONDA_PREFIX/include:$CPLUS_INCLUDE_PATH
    - mkdir -p $HOME/_build
    - cd $HOME/_build
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/lib/ $TRAVIS_BUILD_DIR
    - make

script:
    - make test
    - make install
    - mkdir $HOME/bin
    - tar -jvcf $HOME/bin/triqs_$CC.tar.bz2 $HOME/lib
