
language: cpp
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty
    packages:
    - clang-3.9
    - clang-format-3.9
    - cmake
    - g++-5
    - g++-6
    - gcc-5
    - gcc-6
    - gfortran
    - git
    - libblas-dev
    - libboost1.55-all-dev
    - libclang-3.9-dev
    - libfftw3-dev
    - libgfortran3
    - libgmp-dev
    - libhdf5-serial-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - openmpi-common
    - openmpi-doc
    - python-dev
    - python-mpi4py
    - python-numpy
    - python-scipy
    - python-sphinx

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.9 60 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-3.9
  - sudo apt-get install -y python-h5py python-jinja2 python-virtualenv python-matplotlib python-tornado python-zmq  python-mako python-clang-3.9  libjs-mathjax valgrind hdf5-tools

install:
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/${CXX} -DPYTHON_INTERPRETER=/usr/bin/python
  # Failing with -DBuild_Documentation=ON -DTESTS_C_WITH_VALGRIND=ON
  - make

script:
    - make test
