sudo: required
dist: trusty
language: cpp
compiler:
    - gcc
    - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-5
    - g++-5
    - cmake
    - libgfortran3
    - gfortran
    - libopenmpi-dev
    - openmpi-bin
    - libfftw3-dev
    - libgmp-dev
    - libhdf5-serial-dev
    - libboost1.55-all-dev
deploy:
  provider: s3
  access_key_id: $AWS_A_KEY
  secret_access_key: $AWS_S_KEY
  bucket: buildbin
  skip_cleanup: true
  region: us-west-2
  endpoint: s3-us-west-2.amazonaws.com
  local_dir: $HOME/bin
  on:
    branch: travis


before_install:
    - if [ "$CXX" == "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi


    #Set anaconda python environment
    - cd $HOME
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - conda update --yes conda
    - conda create --yes -n testenv python=2.7 nomkl numpy scipy matplotlib tornado pyzmq cython h5py pip
    - source activate testenv
    - pip install mako mpi4py


install:
    - export C_INCLUDE_PATH=$HOME/miniconda3/envs/testenv/include:$C_INCLUDE_PATH
    - export CPLUS_INCLUDE_PATH=$HOME/miniconda3/envs/testenv/include:$CPLUS_INCLUDE_PATH
    - mkdir -p $HOME/_build
    - cd $HOME/_build
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/lib/ -DUSE_CPP14=ON $TRAVIS_BUILD_DIR
    - make -j4

script:
    - make test
    - make install
    - mkdir $HOME/bin
    - tar -jvcf $HOME/bin/triqs_$CC.tar.bz2 $HOME/lib
